query AllContentQuery {
  metadata {
    sanityOptions {
      projectId
      dataset
    }
  }
  settings: sanitySiteSettings(id: "siteSettings") {
    homepage {
      id
    }
  }
  info: allSanityContent(
    sort: [
        { by: "content.publishedAt", order: DESC }
        { by: "_createdAt", order: DESC }
      ]
   ){
    edges {
      node {
        id
        content {
          title
          slug {
            current
          }
          mainCategory {
            id
            homepage {
              id
            }
            slug {
              current
            }
            color
          }
        mainImage {
          asset {
            _id
            url
          }
          hotspot {
            x
            y
            width
            height
          }
          crop {
            top
            left
            right
            bottom
          }
        }
          contentBlocks {
            ... on SanityFullPortableTextObject {
              _key
              _type
              _rawContent(resolveReferences: { maxDepth: 7 })
            }
            ... on SanityContentList {
              _key
              _type
              title
              resultsPerPage
              hasPaging
              filterCategory {
                id
                title
              }
            }
          }
        }
      }
    }
  }
}
